### ISSUE TITLE
Итератор по множеству

### ISSUE THREAD

**Issue by lmilunovic** [Ladislav92/Universe-bitset-Politeh-Java-project#1]
Если правильно понимаю, нужно имплементировать интерфейс `Iterable`, а потом разработать метод итератор который бы делал итерацию?

Кроме этого, думаю что мой клас реализован (Надо ещё сделат функцию которая добавляет / удаляет массив, но это достаточно легко).

**Comment by maximpetrov** [comment]
Вам нужно реализовать класс наследник `Iterator`, который будет позволять делать итерацию по Вашему множеству. Метод `iterator()` из интерфейса `Iterable` должен возвращать экземпляр этого класса.

Замечания по классу смотрите [здесь](2)
