### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Ladislav92/Universe-bitset-Politeh-Java-project#2]
1. Мощность множества - это количество элементов в нём, а не мощность универсума. Чтобы узнать мощность универсума тоже стоит сделать метод, но `size()` должен возвращать именно количество имеющихся (exists) в множестве элементов.
1. Если Ваши методы `union`, `intersection` и `complement` не меняют объект, на котором вызываются, а создают новое множество, то нет смысла требовать соответствия мощностей универсумов множеств, можно просто взять больший из двух.
1. Желательно создать аналогичные методы, которые меняли бы объект, на котором вызваны вместо создания нового множества. В этих методах можно, по Вашему желанию, либо запрещать разные размеры у множеств, либо увеличивать размер множества при необходимости. Если Вы решите запретить разные размеры, то вместо возвращения `null` лучше выбрасывать исключение.
1. Метод `complement` у Вас реализует вычитание множеств (difference), а не дополнение. Дополнение - это унарная операция (без второго множества), в результате которой получается множество состоящее из элементов, которых не было во исходном множестве.
1. Методы `union`, `intersection` и `complement` в Вашей реализации множества (набор битов) можно реализовать гораздо эффективнее с помощью побитовых операций прямо над байтами.

**Comment by lmilunovic** [comment]
Спасибо за ответ. Да, уже понял что можно быть еффективнее, но в этом случае нужно открыт имплементацию и ползователь может узнать что в классе массив байтов, поетому я выбрал менее ефективную имплементацию. Если нужно, я переделаю.

**Comment by maximpetrov** [comment]
Как раз нет, реализацию открывать не нужно. Если Вы просто реализуете методы через побитовые операции, то интерфейс для пользователя никак не изменится.

**Comment by lmilunovic** [comment]
Да, сейчас понял, моя ошибка.
