### ISSUE TITLE
Сделал улучшение 

### ISSUE THREAD

**Issue by lmilunovic** [Ladislav92/Universe-bitset-Politeh-Java-project#4]
Уважаемый, 
Переделал методы как вы сказали и имплементировал итератор. Прошу вас посмотреть их.
Случайно сделал merge и сейчас у меня больше файлов в репоситорие чем нужно.
В v2Branch находятся мой код. Надо смотрет только Universe и UniverseTest.
Я новый на Гит Хабе поетому я сделал много ошибок в репоситорие,  если надо могу переделат репоситорий.

**Comment by maximpetrov** [comment]
1. В методах `setElement` и `unsetElement` для массивов не очень понятно, почему, если длина входного массива больше мощности универсума множества, то возвращается -1. Во-первых, элементы массива, теоретически, могут повторяться и при этом все входить в область допустимых значений множества. Во-вторых, если массив меньшей длины, то Вы просто пытаетесь проигнорировать элементы, не входящие в область допустимых значений. То есть нужно привести методы к такому виду, чтобы они либо просто игнорировали элементы вне области видимости, либо возвращали ошибку при нахождении первого такого элемента независимо от размера входного массива.
1. В случае ошибки в этих методах лучше выбрасывать исключение, а не возвращать -1.
1. В этих методах проверки на вхождение в диапазон и существование элемента - лишние. Можно сразу вызвать метод для добавления/удаления одного элемента и посмотреть на его результат.
1. Методы `unite` и `intersect` должны выбрасывать исключение в случае несоответствия мощностей универсумов, а не просто возвращать `false`.
1. Вычитание (difference) и исключающее ИЛИ (XOR) - это немного разные операции и метод `difference` у Вас работает неправильно: если с его помощью вычесть два множества, то в результирующем множестве появятся элементы, которых не было в первом множестве, но были во втором.

**Comment by lmilunovic** [comment]
Изменил что Вы сказали. Не уверен что исключения которая мои методы выбрасивают хорошая, надо ли писать своё исключение которое наследует `Exception` класс или это что я сделал достаточно?

**Comment by maximpetrov** [comment]
Всё хорошо, только `difference` у Вас почему-то работает с множествами разных размеров не совсем так, как `intersection` и `union`.
